run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gosec
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
  gosec:
    excludes:
      - G101

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - bodyclose
    - path: store\.go
      text: "G101"
      linters:
        - gosec
