# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gosec
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    # Ignore specific linters in test files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - bodyclose
    # Ignore G101 false positive - "password_resets" is a table name, not credentials
    - linters:
        - gosec
      text: "G101"
