# golangci-lint v2 configuration
# https://golangci-lint.run/docs/configuration/
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gosec
    - misspell
  settings:
    errcheck:
      check-type-assertions: true

issues:
  exclude-generated: lax
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*_test\\.go$"
