# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gosec
    - misspell
  settings:
    errcheck:
      check-type-assertions: true
